
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 21 10:29:05 GMT 2022
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GREATERTHAN = 11;
  public static final int LEFTBRACKET = 3;
  public static final int FUNCTION = 22;
  public static final int MULT = 10;
  public static final int COMMENT = 5;
  public static final int RIGHTBRACKET = 4;
  public static final int INTEGER = 24;
  public static final int NOTEQUAL = 12;
  public static final int INT = 38;
  public static final int OUT = 27;
  public static final int MINUS = 9;
  public static final int SEMICOLON = 7;
  public static final int IS = 25;
  public static final int AND = 15;
  public static final int RECORD = 30;
  public static final int TYPE = 34;
  public static final int COMMA = 6;
  public static final int BEGIN = 16;
  public static final int PUT_LINE = 29;
  public static final int LOOP = 26;
  public static final int IF = 23;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 17;
  public static final int RETURN = 31;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int DOUBLEQ = 2;
  public static final int CONSTANT = 18;
  public static final int COLON = 8;
  public static final int ELSE = 19;
  public static final int ACCESS = 14;
  public static final int WHILE = 35;
  public static final int THEN = 32;
  public static final int ASIGN = 13;
  public static final int END = 20;
  public static final int STRING = 37;
  public static final int FALSE = 21;
  public static final int PROCEDURE = 28;
}

