
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 23 18:07:37 BST 2022
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GREATERTHAN = 13;
  public static final int LEFTBRACKET = 3;
  public static final int FUNCTION = 25;
  public static final int MULT = 11;
  public static final int COMMENT = 5;
  public static final int RIGHTBRACKET = 4;
  public static final int INTEGER = 27;
  public static final int NOTEQUAL = 15;
  public static final int INT = 41;
  public static final int OUT = 30;
  public static final int MINUS = 10;
  public static final int SEMICOLON = 7;
  public static final int IS = 28;
  public static final int AND = 18;
  public static final int RECORD = 33;
  public static final int TYPE = 37;
  public static final int LESSTHAN = 14;
  public static final int COMMA = 6;
  public static final int DIV = 12;
  public static final int BEGIN = 19;
  public static final int PUT_LINE = 32;
  public static final int LOOP = 29;
  public static final int PLUS = 9;
  public static final int IF = 26;
  public static final int ID = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int RETURN = 34;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int DOUBLEQ = 2;
  public static final int CONSTANT = 21;
  public static final int COLON = 8;
  public static final int ELSE = 22;
  public static final int ACCESS = 17;
  public static final int WHILE = 38;
  public static final int THEN = 35;
  public static final int ASIGN = 16;
  public static final int END = 23;
  public static final int STRING = 40;
  public static final int FALSE = 24;
  public static final int PROCEDURE = 31;
}

