
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 23 13:18:12 BST 2022
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PUT_LINE = 24;
  public static final int PROCEDURE = 23;
  public static final int AND = 10;
  public static final int IS = 20;
  public static final int ELSE = 14;
  public static final int PLUS = 2;
  public static final int THEN = 27;
  public static final int WHILE = 30;
  public static final int NOTEQUAL = 8;
  public static final int LOOP = 21;
  public static final int CONSTANT = 13;
  public static final int RETURN = 26;
  public static final int END = 15;
  public static final int TRUE = 28;
  public static final int FUNCTION = 17;
  public static final int IF = 18;
  public static final int ASIGN = 9;
  public static final int BEGIN = 11;
  public static final int BOOLEAN = 12;
  public static final int TYPE = 29;
  public static final int LESSTHAN = 7;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int RECORD = 25;
  public static final int DIV = 5;
  public static final int FALSE = 16;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int INTEGER = 19;
  public static final int OUT = 22;
  public static final int GREATERTHAN = 6;
}

